### ISSUE TITLE
[WIP] Creating or migrating this image to alpine

### ISSUE THREAD

**Issue by cusspvz** [Flowman/docker-pxc#3]
Instead of opening a PR, I've decided to open a issue so we can discuss openly.

## `Dockerfile`

```Dockerfile
FROM alpine:3.3
LABEL authors="Peter Szalatnay <theotherland@gmail.com>, José Moreira <josemoreiravarzim@gmail.com>"

ENV \
    PERCONA_SOURCE_CODE="https://github.com/percona/percona-xtradb-cluster/archive/5.7.tar.gz" \
    BASE_APKS="curl ca-certificates" \
    BUILD_APKS="tar build-base pwgen openssl bsd-compat-headers libstdc++=5.3.0-r0 libaio gnutls ncurses-libs readline-dev libxml2 boost alpine-sdk cmake ncurses-dev gnutls-dev curl-dev libxml2-dev libaio-dev linux-headers bison boost-dev=1.59.0-r0"

RUN \
    echo http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
    apk add $BASE_APKS $BUILD_APKS && \
    update-ca-certificates && \
    mkdir -p /tmp/percona && \
    curl -L $PERCONA_SOURCE_CODE | tar xvzf - --directory /tmp/percona --strip-components=1 && \
    cd /tmp/percona && \
    cmake . && \
    make && \
    apk del $BUILD_APKS

#WIP
```

### [`configure.cmake`](https://github.com/percona/percona-xtradb-cluster/blob/5.7/configure.cmake#L567-L569)
```diff
IF(HAVE_KQUEUE AND HAVE_EVFILT_TIMER)
  SET(HAVE_KQUEUE_TIMERS 1 CACHE INTERNAL "Have kqueue timer-related filter")
ELSEIF(HAVE_TIMER_CREATE AND HAVE_TIMER_SETTIME)
-  IF(HAVE_SIGEV_THREAD_ID OR HAVE_SIGEV_PORT)
+#  IF(HAVE_SIGEV_THREAD_ID OR HAVE_SIGEV_PORT)
    SET(HAVE_POSIX_TIMERS 1 CACHE INTERNAL "Have POSIX timer-related functions")
-  ENDIF()
+#  ENDIF()
ENDIF()
```

**Comment by Flowman** [comment]
I have created a new repository for this https://github.com/Flowman/pxc-alpine.

I went down the road of packaging it properly for alpine.

**Comment by cusspvz** [comment]
Nice, as soon as we get it into alpine's repo, I would love to help you to migrate current image and create an experimental one so we can analise improvements before switching them up.

**Comment by Flowman** [comment]
My plan for the new image is to swap from using giddup and rancher metadata to use etcd so this can be deployed without rancher. And at the same time make it compatible with kubernetes.

**Comment by cusspvz** [comment]
Is there a chance to have both versions of them available?

**Comment by Flowman** [comment]
Sure i can look at keeping a legacy one. But the way forward is to leverage this https://github.com/Percona-Lab/percona-docker/blob/master/pxc-57/entrypoint.sh https://www.percona.com/blog/2016/06/10/percona-xtradb-cluster-in-a-multi-host-docker-network/. It is a better way then using the rancher metadata as you can write information to etcd.

**Comment by Flowman** [comment]
I have finally got PXC working in alpine now :)

Add https://github.com/Flowman/rancher-cataloge to your rancher catalog.
Deploy a Etcd first and then PXC.

What ever you do, do not stop the service as that will put the whole cluster in non-primary mode. Waiting for rancher to implement service graceful shutdown function. PXC has a 10sec delay before stopping mysqld and docker kills the container after 10sec if it does not shutdown.

**Comment by Flowman** [comment]
I will close this as PXC will not get into alpine until 8.0 is release that supports libressl.

Still have the experimental build for alpine 3.6 https://github.com/Flowman/pxc-alpine.

Cheers
